import {
	mobileSmall,
	mobileMedium,
	mobile,
	allMobile,
	tablet,
	portatil,
	portatilLarge,
	matchMediaScreen,
	isMobile,
	isTablet,
	isPortatilSm,
	isPortatilMd,
	isPortatilLg,
} from './deviceDimensions';
import * as DeviceDimension from './deviceDimensions';

import {
	telRegex,
	regexDecimal,
	regexNumbers,
	textUpRegex,
	regexLettersSpacesTildes,
	regexNIT,
	regexDUI,
	regexEmail,
	regexFirstLetterUpperCase,
	regexCelNacional,
	first_letter_uppercase_word,
	validateQuotes,
	validateTel,
	validateDecimal,
	validateNumbers,
	validateCharImage,
	validateUpperCaseLetters,
	validateLetters,
	validateEmailPromise,
	charactersPermited,
	whitespace,
	alphanumeric,
	validarNIT,
	validateEmail,
	verificationDUI,
	setFormatPhone,
	setFormatDUI,
	setFormatNIT,
	validFirstLetterUpperToWord,
	celNacional,
	formatoNumero,
	homologarDui,
	regex,
	validator,
} from './validator';
import * as Validators from './validator';

import {
	addClassElem,
	removeClassElem,
	addClassElements,
	removeClassElements,
	focusElement,
	currentYPosition,
	elmYPosition,
	scrollTo,
} from './manipulationElements';
import * as ManipulationElems from './manipulationElements';

import { setItem, getItem, removeItem, clearStorage } from './localStorage';
import * as LocalStorage from './localStorage';

import {
	removeAccents,
	eliminarDiacriticosEs,
	dateFormatDDMMYY,
	replaceCharacters,
	splitNombre,
	capitalizeWord,
	capitalizeWords,
} from './text';
import * as Text from './text';

import Time from './time';
import Files from './Files';

export {
	mobileSmall,
	mobileMedium,
	mobile,
	allMobile,
	tablet,
	portatil,
	portatilLarge,
	matchMediaScreen,
	isMobile,
	isTablet,
	isPortatilSm,
	isPortatilMd,
	isPortatilLg,
	telRegex,
	regexDecimal,
	regexNumbers,
	textUpRegex,
	regexLettersSpacesTildes,
	regexNIT,
	regexDUI,
	regexEmail,
	regexFirstLetterUpperCase,
	regexCelNacional,
	first_letter_uppercase_word,
	validateQuotes,
	validateTel,
	validateDecimal,
	validateNumbers,
	validateCharImage,
	validateUpperCaseLetters,
	validateLetters,
	validateEmailPromise,
	charactersPermited,
	whitespace,
	alphanumeric,
	validarNIT,
	validateEmail,
	verificationDUI,
	setFormatPhone,
	setFormatDUI,
	setFormatNIT,
	validFirstLetterUpperToWord,
	celNacional,
	formatoNumero,
	homologarDui,
	regex,
	validator,
	addClassElem,
	removeClassElem,
	addClassElements,
	removeClassElements,
	focusElement,
	currentYPosition,
	elmYPosition,
	scrollTo,
	setItem,
	getItem,
	removeItem,
	clearStorage,
	removeAccents,
	eliminarDiacriticosEs,
	dateFormatDDMMYY,
	replaceCharacters,
	splitNombre,
	capitalizeWord,
	capitalizeWords,
	DeviceDimension,
	Validators,
	ManipulationElems,
	LocalStorage,
	Text,
	Time,
	Files,
};

export default {
	DeviceDimension,
	Validators,
	ManipulationElems,
	LocalStorage,
	Text,
	Time,
	Files,
};
